#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-webmock
Version  : 2.1.0
Release  : 7
URL      : https://rubygems.org/downloads/webmock-2.1.0.gem
Source0  : https://rubygems.org/downloads/webmock-2.1.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-addressable
BuildRequires : rubygem-bundler
BuildRequires : rubygem-crack
BuildRequires : rubygem-curb
BuildRequires : rubygem-em-http-request
BuildRequires : rubygem-excon
BuildRequires : rubygem-http
BuildRequires : rubygem-httpclient
BuildRequires : rubygem-minitest
BuildRequires : rubygem-patron
BuildRequires : rubygem-rack
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-simplecov
BuildRequires : rubygem-test-unit
BuildRequires : rubygem-typhoeus

%description
WebMock
=======
[![Gem Version](https://badge.fury.io/rb/webmock.svg)](http://badge.fury.io/rb/webmock) [![Build Status](https://secure.travis-ci.org/bblimke/webmock.svg?branch=master)](http://travis-ci.org/bblimke/webmock) [![Dependency Status](https://gemnasium.com/bblimke/webmock.svg)](http://gemnasium.com/bblimke/webmock) [![Code Climate](https://codeclimate.com/github/bblimke/webmock/badges/gpa.svg)](https://codeclimate.com/github/bblimke/webmock) [![Inline docs](http://inch-ci.org/github/bblimke/webmock.svg?branch=master)](http://inch-ci.org/github/bblimke/webmock)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n webmock-2.1.0
gem spec %{SOURCE0} -l --ruby > rubygem-webmock.gemspec

%build
export LANG=C
gem build rubygem-webmock.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
webmock-2.1.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/webmock-2.1.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/.gemtest
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/.rspec-tm
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/api.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/assertion_failure.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/callback_registry.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/config.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/cucumber.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/deprecation.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/errors.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/http_lib_adapters/curb_adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/http_lib_adapters/em_http_request_adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/http_lib_adapters/excon_adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/http_lib_adapters/http_lib_adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/http_lib_adapters/http_lib_adapter_registry.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/http_lib_adapters/http_rb/client.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/http_lib_adapters/http_rb/request.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/http_lib_adapters/http_rb/response.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/http_lib_adapters/http_rb/streamer.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/http_lib_adapters/http_rb/webmock.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/http_lib_adapters/http_rb_adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/http_lib_adapters/httpclient_adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/http_lib_adapters/manticore_adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/http_lib_adapters/net_http.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/http_lib_adapters/net_http_response.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/http_lib_adapters/patron_adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/http_lib_adapters/typhoeus_hydra_adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/matchers/hash_including_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/minitest.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/rack_response.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/request_body_diff.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/request_execution_verifier.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/request_pattern.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/request_registry.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/request_signature.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/request_signature_snippet.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/request_stub.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/response.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/responses_sequence.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/rspec/matchers.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/rspec/matchers/request_pattern_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/rspec/matchers/webmock_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/stub_registry.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/stub_request_snippet.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/test_unit.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/util/hash_counter.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/util/hash_keys_stringifier.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/util/hash_validator.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/util/headers.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/util/json.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/util/query_mapper.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/util/uri.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/util/version_checker.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/lib/webmock/webmock.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/minitest/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/minitest/test_webmock.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/minitest/webmock_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/curb/curb_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/curb/curb_spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/em_http_request/em_http_request_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/em_http_request/em_http_request_spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/excon/excon_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/excon/excon_spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/http_rb/http_rb_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/http_rb/http_rb_spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/httpclient/httpclient_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/httpclient/httpclient_spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/manticore/manticore_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/manticore/manticore_spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/net_http/net_http_shared.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/net_http/net_http_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/net_http/net_http_spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/net_http/real_net_http_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/patron/patron_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/patron/patron_spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/shared/allowing_and_disabling_net_connect.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/shared/callbacks.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/shared/complex_cross_concern_behaviors.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/shared/enabling_and_disabling_webmock.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/shared/precedence_of_stubs.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/shared/request_expectations.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/shared/returning_declared_responses.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/shared/stubbing_requests.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/typhoeus/typhoeus_hydra_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/typhoeus/typhoeus_hydra_spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/acceptance/webmock_shared.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/fixtures/test.txt
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/quality_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/support/example_curl_output.txt
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/support/failures.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/support/my_rack_app.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/support/network_connection.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/support/webmock_server.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/unit/api_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/unit/errors_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/unit/http_lib_adapters/http_lib_adapter_registry_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/unit/http_lib_adapters/http_lib_adapter_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/unit/matchers/hash_including_matcher_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/unit/rack_response_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/unit/request_body_diff_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/unit/request_execution_verifier_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/unit/request_pattern_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/unit/request_registry_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/unit/request_signature_snippet_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/unit/request_signature_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/unit/request_stub_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/unit/response_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/unit/stub_registry_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/unit/stub_request_snippet_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/unit/util/hash_counter_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/unit/util/hash_keys_stringifier_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/unit/util/headers_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/unit/util/json_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/unit/util/query_mapper_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/unit/util/uri_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/unit/util/version_checker_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/spec/unit/webmock_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/test/http_request.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/test/shared_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/test/test_webmock.rb
/usr/lib64/ruby/gems/2.3.0/gems/webmock-2.1.0/webmock.gemspec
/usr/lib64/ruby/gems/2.3.0/specifications/webmock-2.1.0.gemspec
